### ISSUE TITLE
Resource exhausted

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-chronicles-tail#3]
a `ctail cat local_testnet_data/log0.txt` can lead to resource exhaustion.

![image](https://user-images.githubusercontent.com/22738317/81084750-96b89680-8ef6-11ea-9c67-3a186ee6f123.png)

Log produced by https://github.com/status-im/nim-beacon-chain/blob/c548b90a0e73df89a6ae73c2b9beef4209d7767a/scripts/launch_local_testnet.sh (for a successful finalization so it's not the assert).

**Comment by zah** [comment]
This was fixed in https://github.com/status-im/nim-chronicles-tail/commit/c48735258665a8e54ecf386fd98f437c1ba04269
